= Database report for abvar\fq_isog =

Prepared with the lmfdb asciidoc report tool

Christopher Brady <C.S.Brady@Warwick.ac.uk>

Version 1.0.0

'''

== Collection information ==

[width="50%", ]
|==============================
a|*Description* a| Isogeny classes of abelian varities over finite fields
a|*Status* a| http://beta.lmfdb.org/Variety/Abelian/Fq/[beta]
a|*Contact* a| https://github.com/roed314[David Roe]
a|*Code* a| https://github.com/LMFDB/lmfdb/tree/master/lmfdb/abvar/fq[abvar/fq]
|==============================

== List of keys in the database ==

The following keys appear in at least one record in the database

[WARNING]
====
The type of the keys is inferred from only one record in the database. If the key can have different types in different records this type will be inaccurate
Only the first 100 characters of the example record are shown
====

[width="90%", options="header", ]
|==============================
a|Key a| Inferred Type a| Example record a| Description
a|A_counts a| collection of integer a| `[1, 577, 195301, 6045229, 891243181, 79220139931L, 4189948510987L, 345796535402469L, 188503571953396` ... a| The number of points of the abelian variety over extensions of F_q. Counts are given for $A(F_{q^n})$ for $1 \le n \le max(g,10)$;
a|angle_numbers a| collection of real a| `[0.3459771436386068, 0.596502288733177]` a| Frobenius angle numbers. The positive arguments of the roots (considered as complex numbers) of the Weil L-polynomial.  There will be g of them unless the list includes 0 or pi.
a|angle_ranks a| integer a| `2` a| This is one less than the dimension of the space spanned by the arguments of the roots of the Weil polynomial divided by $\pi$ and one. This might be empty if we haven't computed it yet.
a|brauer_invariants a| collection of integer stored as string a| `[u'0', u'0']` a| The Brauer invariants of the endomorphism algebra. For a simple isogeny class, the number of invariants is the number of primes above p in the number field defined by the Weil polynomial. For a non simple class, the Brauer invariants of its simple factors are concatenated, and they appear in the order in which the factors appear in the field decomposition.
a|C_counts a| collection of integer a| `[1, 1, 4, 5, -19, 82, 106, 253, 490, 911]` a| The number of points of a corresponding curve. If the variety is a Jacobian, these are the point counts of a genus g curve of which this is the Jacobian.  In particular, if any point counts are negative then this abelian variety cannot be a Jacobian.
a|decomposition a| collection of mixed types a| `[[u'1.101.a', 1]]` a| The decomposition into simple factors. The first entry in each pair is the label of the factor, the second is its multiplicity.
a|g a| integer a| `2` a| Genus. The degree of the Weil L-polynomial is 2g
a|galois_n a| integer a| `4` a| The degree label of the Galois group of the Weil polynomial. If the number field was not in the database when the isogeny class was added to the database, this string is empty. If the isogeny class is not simple, this is also an empty string.
a|galois_t a| integer a| `3` a| The transitive label of the Galois group of the Weil polynomial. If the number field was not in the database when the isogeny class was added to the database, this string is empty. If the isogeny class is not simple, this is also an empty string.
a|known_jacobian a| integer a| `-1` a| An integer encoding whether the abelian variety is a Jacobian. 1 means that it is definitely a Jacobian, -1 that it is definitely not, and 0 indicates uncertainty.
a|label a| string a| `1.101.a` a| LMFDB Label. http://beta.lmfdb.org/Variety/Abelian/Fq/Labels[Labeling Scheme]
a|number_field a| string a| `4.0.16317.1` a| The label of the number field defined by the Weil polynomial. If the number field was not in the database when the isogeny class was added to the database, this string is empty. If the isogeny class is not simple, this is also an empty string.
a|p_rank a| integer a| `0` a| The $p$-rank of the abelian variety. The rank of the $p$-torsion subgroup of the abelian variety.  Equal to the number of occurences of the slope 0 in the Newton slopes.
a|places a| collection of mixed types a| `[[[u'1', u'19/9', u'11/9', u'25/9'], [u'1', u'5/3', u'7/3', u'8/3']]]` a| The ideals corresponding to the Brauer invariants of the endomorphism algebra. The outer set of lists corresponds to the simple factors of the isogeny class (so in the example, this isogeny class is a product of two simple isogeny classes). For each simple factor, the list contains one list per prime above p in the number field defined by the Weil polynomial. This list describes the prime ideal above p by giving the second generator of the ideal (the first generator is p), as a list of the coefficients of the generator when written in terms of a specific basis for the number field. This basis contains the powers of a root of the P-polynomial (which is the Weil polynomial but reversed)
a|polynomial a| collection of integer a| `[1, -58, 1263, -12238, 44521]` a| Coefficients of the Weil L-polynomial. The first entry will always be 1 and the last $q^g$.  For i between 0 and g, $a_{2g-i} = q^{g-i} a_i$.
a|primitive_models a| non-primitive type (<type 'list'>) a| `[]` a| Every isogeny class defined over smaller fields such that this isogeny class is a base change of this isogeny class. If the isogeny class is primitive, the list is empty. Otherwise, the list contains the label of every primitive isogeny class that base changes to this class. This list is complete.
a|principally_polarizable a| integer a| `-1` a| An integer encoding whether the abelian variety is principally polarizable. 1 means that it is definitely principally polarizable, -1 that it is definitely not, and 0 indicates uncertainty.
a|q a| integer a| `9` a| Cardinality of Field. All of the roots of the Weil L-polynomial have absolute value $1/\sqrt{q}$.
a|slopes a| collection of integer stored as string a| `[u'0', u'0', u'1', u'1']` a| The slopes of the Newton polygon of the Weil polynomial. The slopes are in increasing order, are symmetric under the involution $s \to 1-s$, and the corresponding Newton polygon has endpoints (0,0) and (2g,g).
|==============================

'''

== List of indices ==

[width="90%", options="header", ]
|==============================
a|Index Name a| Index fields
a|polynomial_1 a| polynomial sorted ascending
a|decomposition_1 a| decomposition sorted ascending
a|p_rank_1 a| p_rank sorted ascending
a|C_counts_1 a| C_counts sorted ascending
a|_id_ a| _id sorted ascending
a|principally_polarizable_1 a| principally_polarizable sorted ascending
a|slopes_1 a| slopes sorted ascending
a|label_1 a| label sorted ascending
a|known_jacobian_1 a| known_jacobian sorted ascending
a|A_counts_1 a| A_counts sorted ascending
|==============================

'''

== List of record types in the database ==

****
[discrete]
=== All records ===

[NOTE]
====
1367543 records of type
====

* A_counts 
* angle_numbers 
* angle_ranks 
* brauer_invariants 
* C_counts 
* decomposition 
* g 
* galois_n 
* galois_t 
* known_jacobian 
* label 
* number_field 
* p_rank 
* places 
* polynomial 
* primitive_models 
* principally_polarizable 
* q 
* slopes 



****

'''

== Notes ==

@@abvar\fq_isog\(NOTES)\description@@

