= Database report for abvar\fq_isog_stats =

Prepared with the lmfdb asciidoc report tool

Christopher Brady <C.S.Brady@Warwick.ac.uk>

Version 1.0.0

'''

== Collection information ==

[width="50%", ]
|==============================
a|*Description* a| @@abvar\fq_isog_stats\(INFO)\description@@
a|*Status* a| @@abvar\fq_isog_stats\(INFO)\status@@
a|*Contact* a| @@abvar\fq_isog_stats\(INFO)\contact@@
a|*Code* a| @@abvar\fq_isog_stats\(INFO)\code@@
|==============================

== List of keys in the database ==

The following keys appear in at least one record in the database

[WARNING]
====
The type of the keys is inferred from only one record in the database. If the key can have different types in different records this type will be inaccurate
Only the first 100 characters of the example record are shown
====

[width="90%", options="header", ]
|==============================
a|Key a| Inferred Type a| Example record a| Description
a|counts a| collection of integer a| `{u'211': [0, 59, 32742], u'131': [0, 45, 16030], u'137': [0, 47, 17142], u'499': [0, 89], u'139': [0` ...
 a| @@abvar\fq_isog_stats\counts\description@@
a|label a| string a| `counts`
 a| @@abvar\fq_isog_stats\label\description@@
|==============================

'''

== List of indices ==

[width="90%", options="header", ]
|==============================
a|Index Name a| Index fields
a|_id_ a| _id sorted ascending
|==============================

'''

== List of record types in the database ==

****
[discrete]
=== All records ===

[NOTE]
====
1 records of type
====

* counts 
* label 



****

'''

== Notes ==

@@abvar\fq_isog_stats\(NOTES)\description@@

