= Database report for bmfs\dimensions =

Prepared with the lmfdb asciidoc report tool

Christopher Brady <C.S.Brady@Warwick.ac.uk>

Version 1.0.0

'''

== Collection information ==

[width="50%", ]
|==============================
a|*Description* a| Bianchi modular forms
a|*Status* a| https://github.com/LMFDB/lmfdb/issues/1431#issuecomment-225529987[future]
a|*Contact* a| https://github.com/JohnCremona[John Cremona]
a|*Code* a| none
|==============================

== List of keys in the database ==

The following keys appear in at least one record in the database

[WARNING]
====
The type of the keys is inferred from only one record in the database. If the key can have different types in different records this type will be inaccurate
Only the first 100 characters of the example record are shown
====

[width="90%", options="header", ]
|==============================
a|Key a| Inferred Type a| Example record a| Description
a|dimension_data a| collection of integer a| `{u'2': {u'cuspidal_dim': 0, u'new_dim': 0}}`
 a| dimension data. Keys are weights, values are dicts with keys 'cuspidal_dim' and 'new_dim', values ints
a|field_absdisc a| integer a| `3`
 a| @@bmfs\dimensions\field_absdisc\description@@
a|field_label a| string a| `2.0.4.1`
 a| LMFDB label of the underlying field
a|label a| string a| `2.0.4.1-11981.1209.1`
 a| full label of the level
a|level_label a| string a| `11981.1209.1`
 a| label of the level ideal
a|level_norm a| integer a| `1`
 a| norm of the level ideal
|==============================

'''

== List of indices ==

[width="90%", options="header", ]
|==============================
a|Index Name a| Index fields
a|field_absdisc_1 a| field_absdisc sorted ascending
a|_id_ a| _id sorted ascending
a|level_norm_1 a| level_norm sorted ascending
|==============================

'''

== List of record types in the database ==

****
[discrete]
=== All records ===

[NOTE]
====
134403 records of type
====

* dimension_data 
* field_absdisc 
* field_label 
* label 
* level_label 
* level_norm 



****

'''

== Notes ==

@@bmfs\dimensions\(NOTES)\description@@

