= Database report for curve_automorphisms\passports =

Prepared with the lmfdb asciidoc report tool

Christopher Brady <C.S.Brady@Warwick.ac.uk>

Version 1.0.0

'''

== Collection information ==

[width="50%", ]
|==============================
a|*Description* a| Group actions on higher genus curves
a|*Status* a| http://beta.lmfdb.org/HigherGenus/C/aut/[alpha]
a|*Contact* a| https://github.com/jenpaulhus[Jen Paulhus]
a|*Code* a| http://link.com[higher_genus_w_automorphisms]
|==============================

== List of keys in the database ==

The following keys appear in at least one record in the database

[WARNING]
====
The type of the keys is inferred from only one record in the database. If the key can have different types in different records this type will be inaccurate
Only the first 100 characters of the example record are shown
====

[width="90%", options="header", ]
|==============================
a|Key a| Inferred Type a| Example record a| Description
a|cc a| collection of integer a| `[1, 1]` a| ordered pair of positive integers where first number is which refined passport and second is which generating vector for that conjugacy class list
a|cinv a| collection of integer a| `[2, 3, 1]` a| trigonal automorphism (if cyclic trigonal), sotred as a list of positive intgers representing a permutation
a|con a| comma separated list of mixed types stored as string a| `[2,2,2,2,2,2]` a| list of conjugacy classes where the action for this particular refined passport occurs, stored as a string representing a list of positive integers
a|cyclic_trigonal a| boolean a| `False` a| True/False whether curve is cyclic trigonal
a|dim a| integer a| `0` a| dimension of the family of curves, this is a non-negative integer
a|eqn a| collection of string a| `[u'y^2=x(x^{4}+a_{1}x^{3}+a_{2}x^{2}+a_{3}x + 1)']` a| string representing an equation for the family, given in LaTeX notation
a|full_auto a| string a| `[12,4]` a| group id for the full automorphism group for this family, as string representing a pair of integers encoding the GAP/Magma group id
a|full_label a| string a| `2.12-4.0.2-2-2-3` a| label for full automorphism group, in same form as label but for full automorphism group data
a|g0 a| integer a| `0` a| quotient genus, this is a non-negative integer
a|gen_vectors a| collection of integer a| `[[2, 1], [2, 1], [2, 1], [2, 1], [2, 1], [2, 1]]` a| generating vector for this action, stored as r lists of positive integers representing permutations
a|genus a| integer a| `2` a| genus of the family of curves, this is a positive integer > 1
a|group a| string a| `[10,1]` a| automorphism group, string representing a pair of integers encoding the GAP/Magma group id
a|hyp_involution a| collection of integer a| `[2, 1]` a| hyperelliptic involution (if hyperelliptic), stored as list of positive integers representing a permutation
a|hyperelliptic a| boolean a| `False` a| True/False whether curve is hyperelliptic
a|jacobian_decomp a| collection of integer a| `[[2, 1, 2]]` a| @@curve_automorphisms\passports\jacobian_decomp\description@@
a|label a| string a| `10.10-1.0.2-2-2-2-2-2-5` a| label for whole family, string of form 'g.a-b.g0.m1-m2-...-mr' where g is genus, a-b is group, g0 is quotient genus, and m1, ..., mr are remaining r entries in signature
a|ndim a| integer a| `3` a| @@curve_automorphisms\passports\ndim\description@@
a|passport_label a| string a| `10.10-1.0.2-2-2-2-2-2-5.1` a| label for the passport (numbered by conjugacy class), string of form 'g.a-b.g0.m1-m2-...-mr.x' where x is a positive integer representing the conjugacy class list, and assigned when the data is initially generated by increasing numeric values of the conjugacy classes
a|r a| integer a| `6` a| number of branch points of the cover, positive integer
a|signature a| comma separated list of mixed types stored as string a| `[0,10,10,10,10]` a| a string representing a list of non-negative integers [g0,m1,...,mr] where g0 is the quotient genus, and the mi represent the orders of the generators of the monodromy group
a|signH a| comma separated list of mixed types stored as string a| `[0,2,2,2,3]` a| signature of full action, a string representing a list of positive integers for the action of the full automorphism group of this family
a|total_label a| string a| `2.2-1.0.2-2-2-2-2-2.1.1` a| label including which generating vector, string of form 'g.a-b.g0.m1-m2-...-mr.x.y' where y is a positive integer representing the particular generating vector for a given refined passport, the value is assigned when the data is initially generated in the order the generating vectors are found
|==============================

'''

== List of indices ==

[width="90%", options="header", ]
|==============================
a|Index Name a| Index fields
a|passport_label_1 a| passport_label sorted ascending
a|group_1 a| group sorted ascending
a|hyperelliptic_1 a| hyperelliptic sorted ascending
a|_id_ a| _id sorted ascending
a|genus_1 a| genus sorted ascending
a|label_1 a| label sorted ascending
a|signature_1 a| signature sorted ascending
a|dim_1 a| dim sorted ascending
|==============================

'''

== List of record types in the database ==

4 distinct record types are present.

****
[discrete]
=== Base record ===

[NOTE]
====
The base record represents the smallest intersection of all related records.


====

Base record class does not exist in the database. Please consult the derived records section below to see all of the classes in the database

* cc 
* con 
* dim 
* eqn 
* g0 
* gen_vectors 
* genus 
* group 
* jacobian_decomp 
* label 
* ndim 
* passport_label 
* r 
* signature 
* total_label 



****

'''

=== Derived records ===

[NOTE]
====
Derived records are the record types that actually exist in the database.They are represented as differences from the base record
====

****
[discrete]
=== @@curve_automorphisms\passports\3d54259a918405cafa4843b1a88e1655\name@@ ===

[NOTE]
====
@@curve_automorphisms\passports\3d54259a918405cafa4843b1a88e1655\description@@


====

22595 records extended from base type

* cyclic_trigonal 
* hyperelliptic 



****

'''

****
[discrete]
=== @@curve_automorphisms\passports\4f8beef0bfa53f182bfd0225a7952461\name@@ ===

[NOTE]
====
@@curve_automorphisms\passports\4f8beef0bfa53f182bfd0225a7952461\description@@


====

3244 records extended from base type

* full_auto 
* full_label 
* signH 



****

'''

****
[discrete]
=== @@curve_automorphisms\passports\609847b5fb1c243bca8a34e7cdaf5db2\name@@ ===

[NOTE]
====
@@curve_automorphisms\passports\609847b5fb1c243bca8a34e7cdaf5db2\description@@


====

670 records extended from base type

* cyclic_trigonal 
* hyp_involution 
* hyperelliptic 



****

'''

****
[discrete]
=== @@curve_automorphisms\passports\a7365892c84fcd06c46455426d64dbcc\name@@ ===

[NOTE]
====
@@curve_automorphisms\passports\a7365892c84fcd06c46455426d64dbcc\description@@


====

611 records extended from base type

* cinv 
* cyclic_trigonal 
* hyperelliptic 



****

'''

== Notes ==

@@curve_automorphisms\passports\(NOTES)\description@@

