= Database report for elliptic_curves\curves =

Prepared with the lmfdb asciidoc report tool

Christopher Brady <C.S.Brady@Warwick.ac.uk>

Version 1.0.0

'''

== Collection information ==

[width="50%", ]
|==============================
a|*Description* a| Elliptic curves over *Q* and other number fields
a|*Status* a| http://www.lmfdb.org/EllipticCurve/[production]
a|*Contact* a| https://github.com/JohnCremona[John Cremona]
a|*Code* a| https://github.com/LMFDB/lmfdb/tree/master/lmfdb/elliptic_curves/[elliptic_curves]
|==============================

== List of keys in the database ==

The following keys appear in at least one record in the database

[WARNING]
====
The type of the keys is inferred from only one record in the database. If the key can have different types in different records this type will be inaccurate
Only the first 100 characters of the example record are shown
====

[width="90%", options="header", ]
|==============================
a|Key a| Inferred Type a| Example record a| Description
a|2adic_gens a| non-primitive type (<type 'list'>) a| `[]`
 a| list of matrices in GL(2,Z/2^nZ) generating the image (None for CM curves).
a|2adic_index a| integer a| `1`
 a| index in GL(2,Z2) of the 2-adicrepresentation (or 0 for CM curves)
a|2adic_label a| string a| `X1`
 a| Rouse label of the associated modular curve (None for CM curves). Based on Rouse, Zureik-Brown classification
a|2adic_log_level a| integer a| `0`
 a| the smallest n such that the image contains the kernel of reduction modulo 2^n
a|ainvs a| collection of integer stored as string a| `[u'0', u'-1', u'1', u'-10', u'-20']`
 a| a-invariants. 5 Weierstrass coefficients as NFelt-strings, joined by ';'
a|anlist a| collection of integer a| `[0, 1, -2, -1, 2, 1, 2, -2, 0, -2, -2, 1, -2, 4, 4, -1, -4, -2, 4, 0, 2]`
 a| L-series coefficients. a_n for 0<=np<20
a|aplist a| collection of integer a| `[-2, -1, 1, -2, 1, 4, -2, 0, -1, 0, 7, 3, -8, -6, 8, -6, 5, 12, -7, -3, 4, -10, -6, 15, -7]`
 a| Traces of Frobenius. a_p for p
a|class_deg a| integer a| `25`
 a| @@elliptic_curves\curves\class_deg\description@@
a|class_size a| integer a| `3`
 a| @@elliptic_curves\curves\class_size\description@@
a|cm a| integer a| `-163`
 a| CM code. 0 (for no CM), or a negative discriminant
a|conductor a| integer a| `11`
 a| Conductor
a|degree a| integer a| `1`
 a| degree of modular parametrization
a|equation a| string a| `\( y^2 + y = x^{3} -  x^{2} - 10 x - 20  \)`
 a| Weierstrass equation
a|galois_images a| collection of string a| `[u'5Cs.1.1']`
 a| Sutherland codes for the images of the mod p Galois representations for the non-surjective primes. Sutherland notation; for CM curves, only primes
a|gens a| list of strings representing points a| `[]`
 a| Generators of infinite order. May be missing
a|heights a| non-primitive type (<type 'list'>) a| `[]`
 a| Heights of generators. May be missing
a|iso a| string a| `100002a`
 a| Cremona isogeny class code
a|iso_nlabel a| integer a| `0`
 a| numerical version of the LMFDB isogeny class label
a|isogeny_degrees a| collection of integer a| `[1, 2, 3, 6, 9, 18]`
 a| @@elliptic_curves\curves\isogeny_degrees\description@@
a|isogeny_matrix a| collection of integer a| `[[1, 5, 25], [5, 1, 5], [25, 5, 1]]`
 a| isogeny matrix
a|iwdata a| dictionary with keys ints, values lists of ints a| `{u'11': [1, 0], u'3': [0, 0], u'2': [0, 1, 0], u'5': [0, 1]}`
 a| Iwasawa invariants. Keys are primes, including all bad multiplicative primes and all primes up to some bound
a|iwp0 a| integer a| `7`
 a| Iwasawa prime. if nonzero, a prime p0 such that lambda=mu=0 for all good p>=p0
a|jinv a| string representing a rational a| `-1/10010`
 a| j-invariant.
a|label a| string a| `100002a1`
 a| Cremona label
a|lmfdb_iso a| string a| `100.a`
 a| LMFDB isogeny class code
a|lmfdb_label a| string a| `100.a1`
 a| LMFDB label
a|lmfdb_number a| integer a| `1`
 a| LMFDB curve number within its class
a|local_data a| list of dicts, one per prime, each with keys 'p' (value:int),'ord_cond' (value: int), 'ord_disc' (value: int), 'ord_den_j' (value:int), 'red' (value: int), 'cp' (value: int), 'kod' (value:string) a| `[{u'ord_disc': 5, u'ord_cond': 1, u'kod': u'\( I_{5} \)', u'ord_den_j': 5, u'p': 11, u'cp': 5, u'roo` ...
 a| reduction data at bad primes
a|min_quad_twist a| collection of mixed types a| `{u'disc': 1, u'label': u'11a1'}`
 a| minimal quadratic twist
a|mod-p_images a| collection of string a| `[u'5Cs.1.1']`
 a| Sutherland codes for the images of the mod p Galois representations for the non-maximal primes
a|non-maximal_primes a| non-primitive type (<type 'list'>) a| `[]`
 a| primes p for which the mod p Galois representation is not maximal
a|non-surjective_primes a| non-primitive type (<type 'list'>) a| `[]`
 a| primes p for which the mod p Galois representation is not surjective
a|number a| integer a| `1`
 a| Cremona curve number within its class
a|rank a| integer a| `0`
 a| rank
a|real_period a| real a| `1.26920930428`
 a| Real period (approximate)
a|regulator a| integer a| `1.0`
 a| Regulator. May be missing; Approximate if rank>0
a|sha a| integer a| `1`
 a| analytic order of sha (rounded value of sha_an)
a|sha_an a| integer a| `1.0`
 a| analytic order of Sha, approximate unless rank<2
a|sha_primes a| non-primitive type (<type 'list'>) a| `[]`
 a| primes dividing sha. N^k  (k>;0)
a|signD a| integer a| `-1`
 a| sign of Discriminant in {-1,+1}
a|special_value a| real a| `0.253841860856`
 a| special value of r'th derivative ofL-function (divided by r!) (approximate)
a|tamagawa_product a| integer a| `5`
 a| Tamagawa product
a|torsion a| integer a| `1`
 a| torsion order
a|torsion_generators a| collection of string a| `[u'(5, 5)']`
 a| generators of torsion subgroup
a|torsion_primes a| collection of integer a| `[5]`
 a| primes dividing torsion
a|torsion_structure a| non-primitive type (<type 'list'>) a| `[]`
 a| invariants of torsion subgroup
a|x-coordinates_of_integral_points a| string a| `[5,16]`
 a| x-coordinates of integral points
a|xainvs a| comma separated list of mixed types stored as string a| `[0,-1,0,-1,-1023]`
 a| a-invariants (coefficients of minimal reduced Weierstass model)
|==============================

'''

== List of indices ==

[width="90%", options="header", ]
|==============================
a|Index Name a| Index fields
a|isogeny_degrees_1 a| isogeny_degrees sorted ascending
a|xainvs_1 a| xainvs sorted ascending
a|cm_1 a| cm sorted ascending
a|number_1 a| number sorted ascending
a|jinv_1 a| jinv sorted ascending
a|label_1 a| label sorted ascending
a|non-maximal_primes_1 a| non-maximal_primes sorted ascending
a|conductor_1_iso_nlabel_1_lmfdb_number_1 a| conductor sorted ascending, iso_nlabel sorted ascending, lmfdb_number sorted ascending
a|rank_1 a| rank sorted ascending
a|_id_ a| _id sorted ascending
a|label_1_number_1 a| label sorted ascending, number sorted ascending
a|torsion_1 a| torsion sorted ascending
a|non-surjective_primes_1 a| non-surjective_primes sorted ascending
a|rank_1_number_1 a| rank sorted ascending, number sorted ascending
a|lmfdb_label_1 a| lmfdb_label sorted ascending
a|lmfdb_iso_1 a| lmfdb_iso sorted ascending
a|torsion_structure_1 a| torsion_structure sorted ascending
a|lmfdb_number_1 a| lmfdb_number sorted ascending
a|conductor_1 a| conductor sorted ascending
a|iso_1 a| iso sorted ascending
a|sha_1 a| sha sorted ascending
a|lmfdb_label_1_number_1 a| lmfdb_label sorted ascending, number sorted ascending
|==============================

'''

== List of record types in the database ==

4 distinct record types are present.

****
[discrete]
=== Base record : @@elliptic_curves\curves\675da55389429ffe491176d731c53eba\name@@ ===

[NOTE]
====
The base record represents the smallest intersection of all related records.

@@elliptic_curves\curves\675da55389429ffe491176d731c53eba\description@@
====

427438 records of base type in collection

* non-maximal_primes 
* torsion_structure 
* ainvs 
* x-coordinates_of_integral_points 
* cm 
* lmfdb_number 
* xainvs 
* number 
* rank 
* sha_primes 
* mod-p_images 
* galois_images 
* label 
* torsion 
* iso_nlabel 
* min_quad_twist 
* conductor 
* local_data 
* lmfdb_iso 
* 2adic_label 
* heights 
* jinv 
* 2adic_log_level 
* class_deg 
* class_size 
* tamagawa_product 
* sha_an 
* isogeny_degrees 
* torsion_generators 
* degree 
* 2adic_gens 
* torsion_primes 
* signD 
* real_period 
* isogeny_matrix 
* special_value 
* non-surjective_primes 
* 2adic_index 
* equation 
* gens 
* regulator 
* sha 
* iso 
* lmfdb_label 



****

'''

=== Derived records ===

[NOTE]
====
Derived records are the record types that actually exist in the database.They are represented as differences from the base record
====

****
[discrete]
=== @@elliptic_curves\curves\e42aa731a3e271b4079d0b3c89caf9d2\name@@ ===

[NOTE]
====
@@elliptic_curves\curves\e42aa731a3e271b4079d0b3c89caf9d2\description@@


====

658895 records extended from base type

* anlist 
* aplist 
* iwdata 
* iwp0 



****

'''

****
[discrete]
=== @@elliptic_curves\curves\fd84750abcc8da359262aef4278cb3ca\name@@ ===

[NOTE]
====
@@elliptic_curves\curves\fd84750abcc8da359262aef4278cb3ca\description@@


====

1082107 records extended from base type

* anlist 
* aplist 



****

'''

****
[discrete]
=== @@elliptic_curves\curves\03a7e6384d8cd01490373f45ec818429\name@@ ===

[NOTE]
====
@@elliptic_curves\curves\03a7e6384d8cd01490373f45ec818429\description@@


====

315209 records extended from base type

* iwdata 
* iwp0 



****

'''

== Notes ==

@@elliptic_curves\curves\(NOTES)\description@@

