= Database report for hgm\motives_copy =

Prepared with the lmfdb asciidoc report tool

Christopher Brady <C.S.Brady@Warwick.ac.uk>

Version 1.0.0

'''

== Collection information ==

[width="50%", ]
|==============================
a|*Description* a| @@hgm\motives_copy\(INFO)\description@@
a|*Status* a| @@hgm\motives_copy\(INFO)\status@@
a|*Contact* a| @@hgm\motives_copy\(INFO)\contact@@
a|*Code* a| @@hgm\motives_copy\(INFO)\code@@
|==============================

== List of keys in the database ==

The following keys appear in at least one record in the database

[WARNING]
====
The type of the keys is inferred from only one record in the database. If the key can have different types in different records this type will be inaccurate
Only the first 100 characters of the example record are shown
====

[width="90%", options="header", ]
|==============================
a|Key a| Inferred Type a| Example record a| Description
|==============================

'''

== List of indices ==

[width="90%", options="header", ]
|==============================
a|Index Name a| Index fields
a|metadata_1 a| metadata sorted ascending
a|_id_ a| _id sorted ascending
|==============================

'''

== List of record types in the database ==

== Notes ==

@@hgm\motives_copy\(NOTES)\description@@

