= Database report for knowledge\history =

Prepared with the lmfdb asciidoc report tool

Christopher Brady <C.S.Brady@Warwick.ac.uk>

Version 1.0.0

'''

== Collection information ==

[width="50%", ]
|==============================
a|*Description* a| knowledge
a|*Status* a| http://www.lmfdb.org/knowledge[production]
a|*Contact* a| https://github.com/davidfarmer[David Farmer]
a|*Code* a| https://github.com/LMFDB/lmfdb/tree/master/lmfdb/knowledge/[knowledge]
|==============================

== List of keys in the database ==

The following keys appear in at least one record in the database

[WARNING]
====
The type of the keys is inferred from only one record in the database. If the key can have different types in different records this type will be inaccurate
Only the first 100 characters of the example record are shown
====

[width="90%", options="header", ]
|==============================
a|Key a| Inferred Type a| Example record a| Description
a|state a| string a| `saved` a| @@knowledge\history\state\description@@
a|time a| Type cannot be identified (<type 'datetime.datetime'>) a| `2011-10-01 19:39:45.005000` a| @@knowledge\history\time\description@@
a|title a| string a| `Non-singular point (definition)` a| @@knowledge\history\title\description@@
a|who a| string a| `john.jones` a| @@knowledge\history\who\description@@
|==============================

'''

== List of indices ==

[width="90%", options="header", ]
|==============================
a|Index Name a| Index fields
a|time_1 a| time sorted ascending
a|_id_ a| _id sorted ascending
a|metadata_1 a| metadata sorted ascending
|==============================

'''

== List of record types in the database ==

****
[discrete]
=== All records ===

[NOTE]
====
647 records of type
====

* state 
* time 
* title 
* who 



****

'''

== Notes ==

@@knowledge\history\(NOTES)\description@@

