= Database report for Lfunction\LemurellTest =

Prepared with the lmfdb asciidoc report tool

Christopher Brady <C.S.Brady@Warwick.ac.uk>

Version 1.0.0

'''

== Collection information ==

[width="50%", ]
|==============================
a|*Description* a| @@Lfunction\LemurellTest\(INFO)\description@@
a|*Status* a| @@Lfunction\LemurellTest\(INFO)\status@@
a|*Contact* a| @@Lfunction\LemurellTest\(INFO)\contact@@
a|*Code* a| @@Lfunction\LemurellTest\(INFO)\code@@
|==============================

== List of keys in the database ==

The following keys appear in at least one record in the database

[WARNING]
====
The type of the keys is inferred from only one record in the database. If the key can have different types in different records this type will be inaccurate
Only the first 100 characters of the example record are shown
====

[width="90%", options="header", ]
|==============================
a|Key a| Inferred Type a| Example record a| Description
a|primitive a| boolean a| `True` a| @@Lfunction\LemurellTest\primitive\description@@
a|symmetry a| string a| `odd` a| @@Lfunction\LemurellTest\symmetry\description@@
a|Q_fe a| real a| `4.11347027074` a| @@Lfunction\LemurellTest\Q_fe\description@@
a|fricke a| integer a| `1` a| @@Lfunction\LemurellTest\fricke\description@@
a|Character a| integer a| `1` a| @@Lfunction\LemurellTest\Character\description@@
a|sign a| integer a| `-1` a| @@Lfunction\LemurellTest\sign\description@@
a|Llabel a| Record cannot be found containing key a| `N/A` a| @@Lfunction\LemurellTest\Llabel\description@@
a|ObjectLabel a| string a| `GL2Maass_167_0.30117539827` a| @@Lfunction\LemurellTest\ObjectLabel\description@@
a|Dirichlet_coefficients a| collection of real a| `[1.0, -1.8193296011694, -1.0041264596304, 2.309960197264, -0.7100028980671, 1.8268369912969, -1.4272` ... a| @@Lfunction\LemurellTest\Dirichlet_coefficients\description@@
a|kappa_fe a| collection of real a| `[0.5, 0.5]` a| @@Lfunction\LemurellTest\kappa_fe\description@@
a|texname a| string a| `L(s,f)` a| @@Lfunction\LemurellTest\texname\description@@
a|group a| string a| `GL2` a| @@Lfunction\LemurellTest\group\description@@
a|texnamecompleted1ms a| string a| `\Lambda(1-s,f)` a| @@Lfunction\LemurellTest\texnamecompleted1ms\description@@
a|number_of_coef a| integer a| `592` a| @@Lfunction\LemurellTest\number_of_coef\description@@
a|imaginary_shiftsR a| collection of real a| `[0.30117539827, -0.30117539827]` a| @@Lfunction\LemurellTest\imaginary_shiftsR\description@@
a|ObjectUrl a| string a| `/ModularForm/GL2/Q/Maass/GL2Maass_167_0.30117539827` a| @@Lfunction\LemurellTest\ObjectUrl\description@@
a|Precision a| integer a| `9` a| @@Lfunction\LemurellTest\Precision\description@@
a|real_shiftsR a| collection of integer a| `[1, 1]` a| @@Lfunction\LemurellTest\real_shiftsR\description@@
a|label a| Record cannot be found containing key a| `N/A` a| @@Lfunction\LemurellTest\label\description@@
a|selfdual a| boolean a| `True` a| @@Lfunction\LemurellTest\selfdual\description@@
a|Numc a| integer a| `586` a| @@Lfunction\LemurellTest\Numc\description@@
a|imaginary_shiftsC a| non-primitive type (<type 'list'>) a| `[]` a| @@Lfunction\LemurellTest\imaginary_shiftsC\description@@
a|Conrey a| integer a| `1` a| @@Lfunction\LemurellTest\Conrey\description@@
a|real_shiftsC a| non-primitive type (<type 'list'>) a| `[]` a| @@Lfunction\LemurellTest\real_shiftsC\description@@
a|Eigenvalue a| real a| `0.880387550668` a| @@Lfunction\LemurellTest\Eigenvalue\description@@
a|texnamecompleteds a| string a| `\Lambda(s,f)` a| @@Lfunction\LemurellTest\texnamecompleteds\description@@
a|degree a| integer a| `2` a| @@Lfunction\LemurellTest\degree\description@@
a|Level a| integer a| `167` a| @@Lfunction\LemurellTest\Level\description@@
a|precision a| integer a| `8` a| @@Lfunction\LemurellTest\precision\description@@
a|weight a| integer a| `0` a| @@Lfunction\LemurellTest\weight\description@@
a|Contributor a| string a| `Stefan Lemurell` a| @@Lfunction\LemurellTest\Contributor\description@@
a|url a| string a| `/21_1__/167/1.1/0.301175_-0.30117__/` a| @@Lfunction\LemurellTest\url\description@@
a|characternumber a| integer a| `1` a| @@Lfunction\LemurellTest\characternumber\description@@
a|nu_fe a| non-primitive type (<type 'list'>) a| `[]` a| @@Lfunction\LemurellTest\nu_fe\description@@
a|eigenvalue a| real a| `0.30117539827` a| @@Lfunction\LemurellTest\eigenvalue\description@@
a|Symmetry a| string a| `even` a| @@Lfunction\LemurellTest\Symmetry\description@@
a|Weight a| integer a| `0` a| @@Lfunction\LemurellTest\Weight\description@@
a|level a| integer a| `167` a| @@Lfunction\LemurellTest\level\description@@
a|quasidegree a| integer a| `2` a| @@Lfunction\LemurellTest\quasidegree\description@@
a|characterName a| string a| `trivial character` a| @@Lfunction\LemurellTest\characterName\description@@
a|Fricke a| integer a| `-1` a| @@Lfunction\LemurellTest\Fricke\description@@
a|coefficient_type a| integer a| `2` a| @@Lfunction\LemurellTest\coefficient_type\description@@
a|Sign a| integer a| `-1` a| @@Lfunction\LemurellTest\Sign\description@@
a|credit a| string a| `Stefan Lemurell` a| @@Lfunction\LemurellTest\credit\description@@
a|charactermodulus a| integer a| `1` a| @@Lfunction\LemurellTest\charactermodulus\description@@
a|dirichlet_coefficients a| collection of real a| `[1.0, -1.6387526504195, -1.352081557681, 1.6855102491037, 0.6769903652838, 2.2157272363148, 0.049801` ... a| @@Lfunction\LemurellTest\dirichlet_coefficients\description@@
a|software a| string a| `Mathematica` a| @@Lfunction\LemurellTest\software\description@@
|==============================

'''

== List of indices ==

[width="90%", options="header", ]
|==============================
a|Index Name a| Index fields
a|_id_ a| _id sorted ascending
|==============================

'''

== List of record types in the database ==

2 distinct record types are present.

****
[discrete]
=== Base record ===

[NOTE]
====
The base record represents the smallest intersection of all related records.


====

Base record class does not exist in the database. Please consult the derived records section below to see all of the classes in the database

* ObjectUrl 
* ObjectLabel 
* software 



****

'''

=== Derived records ===

[NOTE]
====
Derived records are the record types that actually exist in the database.They are represented as differences from the base record
====

****
[discrete]
=== @@Lfunction\LemurellTest\128ce48c7255b9478efa544e5589f569\name@@ ===

[NOTE]
====
@@Lfunction\LemurellTest\128ce48c7255b9478efa544e5589f569\description@@


====

48 records extended from base type

* Llabel 
* Q_fe 
* characterName 
* charactermodulus 
* characternumber 
* coefficient_type 
* credit 
* degree 
* dirichlet_coefficients 
* eigenvalue 
* fricke 
* group 
* imaginary_shiftsC 
* imaginary_shiftsR 
* kappa_fe 
* label 
* level 
* nu_fe 
* number_of_coef 
* precision 
* primitive 
* quasidegree 
* real_shiftsC 
* real_shiftsR 
* selfdual 
* sign 
* symmetry 
* texname 
* texnamecompleted1ms 
* texnamecompleteds 
* url 
* weight 



****

'''

****
[discrete]
=== @@Lfunction\LemurellTest\556428030d1cf67aeadb252bfeae3ed9\name@@ ===

[NOTE]
====
@@Lfunction\LemurellTest\556428030d1cf67aeadb252bfeae3ed9\description@@


====

48 records extended from base type

* Character 
* Conrey 
* Contributor 
* Dirichlet_coefficients 
* Eigenvalue 
* Fricke 
* Level 
* Numc 
* Precision 
* Sign 
* Symmetry 
* Weight 



****

'''

== Notes ==

@@Lfunction\LemurellTest\(NOTES)\description@@

