= Database report for MaassWaveForms\HT =

Prepared with the lmfdb asciidoc report tool

Christopher Brady <C.S.Brady@Warwick.ac.uk>

Version 1.0.0

'''

== Collection information ==

[width="50%", ]
|==============================
a|*Description* a| @@MaassWaveForms\HT\(INFO)\description@@
a|*Status* a| @@MaassWaveForms\HT\(INFO)\status@@
a|*Contact* a| @@MaassWaveForms\HT\(INFO)\contact@@
a|*Code* a| @@MaassWaveForms\HT\(INFO)\code@@
|==============================

== List of keys in the database ==

The following keys appear in at least one record in the database

[WARNING]
====
The type of the keys is inferred from only one record in the database. If the key can have different types in different records this type will be inaccurate
Only the first 100 characters of the example record are shown
====

[width="90%", options="header", ]
|==============================
a|Key a| Inferred Type a| Example record a| Description
a|Coefficient a| collection of real a| `[1.0, -1.8661616616283976, -0.4037627500310308, 2.4825593473316006, -0.16038791699176383, 0.75348656` ... a| @@MaassWaveForms\HT\Coefficient\description@@
a|Cusp_evs a| collection of integer a| `[1]` a| @@MaassWaveForms\HT\Cusp_evs\description@@
a|Weight a| integer a| `0.0` a| @@MaassWaveForms\HT\Weight\description@@
a|Symmetry a| integer a| `0` a| @@MaassWaveForms\HT\Symmetry\description@@
a|Eigenvalue a| real a| `9.53369526135` a| @@MaassWaveForms\HT\Eigenvalue\description@@
a|Level a| integer a| `1` a| @@MaassWaveForms\HT\Level\description@@
a|Character a| integer a| `1` a| @@MaassWaveForms\HT\Character\description@@
a|Numc a| integer a| `9` a| @@MaassWaveForms\HT\Numc\description@@
a|Contributor a| string a| `HT` a| @@MaassWaveForms\HT\Contributor\description@@
a|Conrey a| integer a| `1` a| @@MaassWaveForms\HT\Conrey\description@@
a|Dimension a| integer a| `1` a| @@MaassWaveForms\HT\Dimension\description@@
a|Norm a| integer a| `1.0` a| @@MaassWaveForms\HT\Norm\description@@
|==============================

'''

== List of indices ==

[width="90%", options="header", ]
|==============================
a|Index Name a| Index fields
a|Numc_1 a| Numc sorted ascending
a|Weight_1 a| Weight sorted ascending
a|Eigenvalue_1 a| Eigenvalue sorted ascending
a|Coefficient_1 a| Coefficient sorted ascending
a|metadata_1 a| metadata sorted ascending
a|_id_ a| _id sorted ascending
a|Level_1 a| Level sorted ascending
|==============================

'''

== List of record types in the database ==

****
[discrete]
=== All records ===

[NOTE]
====
69 records of type
====

* Character 
* Coefficient 
* Conrey 
* Contributor 
* Cusp_evs 
* Dimension 
* Eigenvalue 
* Level 
* Norm 
* Numc 
* Symmetry 
* Weight 



****

'''

== Notes ==

@@MaassWaveForms\HT\(NOTES)\description@@

