= Database report for MaassWaveForms\FS =

Prepared with the lmfdb asciidoc report tool

Christopher Brady <C.S.Brady@Warwick.ac.uk>

Version 1.0.0

'''

== Collection information ==

[width="50%", ]
|==============================
a|*Description* a| Maass wave forms
a|*Status* a| http://www.lmfdb.org/ModularForm/GL2/Q/Maass/[production]
a|*Contact* a| https://github.com/lemurell[Stefan Lemurrell] , https://github.com/fredstro[Fredrik Strömberg]
a|*Code* a| https://github.com/LMFDB/lmfdb/tree/master/lmfdb/modular_forms/maass_forms/maass_waveforms/[modular_forms/maass_forms/maass_waveforms]
|==============================

== List of keys in the database ==

The following keys appear in at least one record in the database

[WARNING]
====
The type of the keys is inferred from only one record in the database. If the key can have different types in different records this type will be inaccurate
Only the first 100 characters of the example record are shown
====

[width="90%", options="header", ]
|==============================
a|Key a| Inferred Type a| Example record a| Description
a|Character a| integer a| `0`
 a| character number in Conrey numbering if Conrey is set to 1 else in Sage ordering
a|Coefficient a| collection of real a| `[0, 1.0, -23.3895804510333, 0.9330420276699, 546.0724736753626, 1.7235525028775, -21.8234615703817,` ...
 a| A short list of Fourier coefficients c(1),c(2),...
a|Conrey a| integer a| `1`
 a| 1 if Conrey character numbers are used, else 0
a|Contributor a| string a| `HT`
 a| identifier of person who originally submitted this data, e.g. 'HT' is Holger Then, FS is Fredrik Stromberg etc. (coefficients may have been added later by other contributors, identified in the corresponding coefficient record)
a|Cusp_evs a| collection of integer a| `[1]`
 a| list of (complex) numbers such that the Fourier coefficients at that cusp are proportional to the ones at infinity with this constant. Such constants exists if the corresponding Atkin-Lehner operators are cusp normalisers. The first '1' corresponds to the cusp at infinity
a|Dim a| integer a| `1`
 a| dimension of the eigenspace containing this Maass form (estimated heuristically / numerically)
a|Dimension a| integer a| `1`
 a| probably a duplicate of Dim
a|Eigenvalue a| real a| `0.038758582`
 a| Spectral parameter R corresponding to this Maass form, s.t. the actual eigenvalue is lambda=1/4+R^2
a|Error a| real a| `6.05071548421e-15`
 a| estimate of the error in the eigenvalue
a|Fricke a| integer a| `1`
 a| @@MaassWaveForms\FS\Fricke\description@@
a|Level a| integer a| `1`
 a| level
a|M0 a| integer a| `0`
 a| the M0 which was used as input to the algorithm for computing the eigenvalue (if set correctly it should be > 0)
a|Newform a| boolean a| `False`
 a| @@MaassWaveForms\FS\Newform\description@@
a|Norm a| integer a| `1.0`
 a| describes the normalisation used for the coefficients, 1.0 means Hecke normalisation so c(1)=1, other} alternatives (not used currently) would be L2-normalisation
a|Numc a| integer a| `0`
 a| number of coefficients available for this form
a|ObjectLabel a| string a| `GL2Maass_107_0.840090994356`
 a| @@MaassWaveForms\FS\ObjectLabel\description@@
a|ObjectUrl a| string a| `/ModularForm/GL2/Q/Maass/GL2Maass_107_0.840090994356`
 a| @@MaassWaveForms\FS\ObjectUrl\description@@
a|Precision a| real a| `1e-09`
 a| @@MaassWaveForms\FS\Precision\description@@
a|Sign a| integer a| `1`
 a| @@MaassWaveForms\FS\Sign\description@@
a|Symmetry a| integer a| `0`
 a| 1 if this Maass form is even and 0 if it is odd
a|Weight a| integer a| `0.0`
 a| the weight of the Maass form
a|Y a| integer a| `0`
 a| the Y which was used as input to the algorithm for computing the eigenvalue (if set correctly it should be > 0)
a|coeff_id a| non-primitive type (<class 'bson.objectid.ObjectId'>) a| `4f87f0f388aece21410000e8`
 a| id of the corresponding coefficient record
a|date a| Type cannot be identified (<type 'datetime.datetime'>) a| `2012-02-27 21:12:35.086000`
 a| @@MaassWaveForms\FS\date\description@@
a|dim a| integer a| `1`
 a| probably a third duplicate of 'Dim' and 'Dimension'
a|software a| string a| `Mathematica`
 a| @@MaassWaveForms\FS\software\description@@
|==============================

'''

== List of indices ==

[width="90%", options="header", ]
|==============================
a|Index Name a| Index fields
a|Numc_1 a| Numc sorted ascending
a|Weight_1 a| Weight sorted ascending
a|Eigenvalue_1 a| Eigenvalue sorted ascending
a|Coefficient_1 a| Coefficient sorted ascending
a|[ ('Weight', 1), ('Level', 1), ('Character', 1), ('Eigenvalue', 1) ]_1 a| [ ('Weight', 1), ('Level', 1), ('Character', 1), ('Eigenvalue', 1) ] sorted ascending
a|Character_1 a| Character sorted ascending
a|metadata_1 a| metadata sorted ascending
a|_id_ a| _id sorted ascending
a|Level_1 a| Level sorted ascending
|==============================

'''

== List of record types in the database ==

10 distinct record types are present.

****
[discrete]
=== Base record ===

[NOTE]
====
The base record represents the smallest intersection of all related records.


====

Base record class does not exist in the database. Please consult the derived records section below to see all of the classes in the database

* Eigenvalue 
* Weight 
* Symmetry 
* Level 
* Character 
* Numc 
* Contributor 



****

'''

=== Derived records ===

[NOTE]
====
Derived records are the record types that actually exist in the database.They are represented as differences from the base record
====

****
[discrete]
=== @@MaassWaveForms\FS\7eb2c46def9082016e51efb821b7e71b\name@@ ===

[NOTE]
====
@@MaassWaveForms\FS\7eb2c46def9082016e51efb821b7e71b\description@@


====

14772 records extended from base type

* Coefficient 
* Conrey 
* Fricke 
* ObjectLabel 
* ObjectUrl 
* Precision 
* Sign 
* software 



****

'''

****
[discrete]
=== @@MaassWaveForms\FS\e40446fa3ccf6e73847e49be5775ddd7\name@@ ===

[NOTE]
====
@@MaassWaveForms\FS\e40446fa3ccf6e73847e49be5775ddd7\description@@


====

1274 records extended from base type

* Conrey 
* Cusp_evs 
* Dim 
* Error 
* M0 
* Y 
* coeff_id 
* date 
* dim 



****

'''

****
[discrete]
=== @@MaassWaveForms\FS\82a45185b6aebd408cd336381c85df53\name@@ ===

[NOTE]
====
@@MaassWaveForms\FS\82a45185b6aebd408cd336381c85df53\description@@


====

383 records extended from base type

* Conrey 
* Cusp_evs 
* Dim 
* Error 
* M0 
* Y 
* coeff_id 
* date 



****

'''

****
[discrete]
=== @@MaassWaveForms\FS\b4e870623b1107a1344c8e9311647943\name@@ ===

[NOTE]
====
@@MaassWaveForms\FS\b4e870623b1107a1344c8e9311647943\description@@


====

68 records extended from base type

* Coefficient 
* Conrey 
* Cusp_evs 
* Dim 
* Dimension 
* Error 
* M0 
* Norm 
* Y 
* coeff_id 
* dim 



****

'''

****
[discrete]
=== @@MaassWaveForms\FS\c5d8e9ccf2a1de473d8fefe9771fae9d\name@@ ===

[NOTE]
====
@@MaassWaveForms\FS\c5d8e9ccf2a1de473d8fefe9771fae9d\description@@


====

48 records extended from base type

* Coefficient 
* Conrey 
* Error 
* Fricke 
* ObjectLabel 
* ObjectUrl 
* Sign 
* software 



****

'''

****
[discrete]
=== @@MaassWaveForms\FS\d1c6b30831fdc26912e811b803a4abb5\name@@ ===

[NOTE]
====
@@MaassWaveForms\FS\d1c6b30831fdc26912e811b803a4abb5\description@@


====

34 records extended from base type

* Conrey 
* Cusp_evs 
* Dim 
* Error 
* M0 
* Y 
* date 



****

'''

****
[discrete]
=== @@MaassWaveForms\FS\dea3dc7ef5b05b6b2e4dda3db026f209\name@@ ===

[NOTE]
====
@@MaassWaveForms\FS\dea3dc7ef5b05b6b2e4dda3db026f209\description@@


====

12 records extended from base type

* Conrey 
* Cusp_evs 
* Dim 
* Error 
* M0 
* Newform 
* Y 
* coeff_id 
* date 



****

'''

****
[discrete]
=== @@MaassWaveForms\FS\aae40e4c40e41235a5f4438e147aade7\name@@ ===

[NOTE]
====
@@MaassWaveForms\FS\aae40e4c40e41235a5f4438e147aade7\description@@


====

6 records extended from base type

* Conrey 
* Cusp_evs 
* Dim 
* Error 
* M0 
* Newform 
* Y 
* coeff_id 
* date 
* dim 



****

'''

****
[discrete]
=== @@MaassWaveForms\FS\957899476aa1ddd2958f61885624e083\name@@ ===

[NOTE]
====
@@MaassWaveForms\FS\957899476aa1ddd2958f61885624e083\description@@


====

1 records extended from base type

* Cusp_evs 
* Dim 
* Error 
* M0 
* Y 
* date 



****

'''

****
[discrete]
=== @@MaassWaveForms\FS\46a9045043e810ea911e43f72e0ff6bb\name@@ ===

[NOTE]
====
@@MaassWaveForms\FS\46a9045043e810ea911e43f72e0ff6bb\description@@


====

1 records extended from base type

* Conrey 
* Cusp_evs 
* Dim 
* Error 
* M0 
* Y 
* dim 



****

'''

== Notes ==

@@MaassWaveForms\FS\(NOTES)\description@@

