= Database report for mod_l_eigenvalues\hecke_algebras_l_adic =

Prepared with the lmfdb asciidoc report tool

Christopher Brady <C.S.Brady@Warwick.ac.uk>

Version 1.0.0

'''

== Collection information ==

[width="50%", ]
|==============================
a|*Description* a| @@mod_l_eigenvalues\hecke_algebras_l_adic\(INFO)\description@@
a|*Status* a| @@mod_l_eigenvalues\hecke_algebras_l_adic\(INFO)\status@@
a|*Contact* a| @@mod_l_eigenvalues\hecke_algebras_l_adic\(INFO)\contact@@
a|*Code* a| @@mod_l_eigenvalues\hecke_algebras_l_adic\(INFO)\code@@
|==============================

== List of keys in the database ==

The following keys appear in at least one record in the database

[WARNING]
====
The type of the keys is inferred from only one record in the database. If the key can have different types in different records this type will be inaccurate
Only the first 100 characters of the example record are shown
====

[width="90%", options="header", ]
|==============================
a|Key a| Inferred Type a| Example record a| Description
a|charpoly_ql a| Record cannot be found containing key a| `N/A` a| @@mod_l_eigenvalues\hecke_algebras_l_adic\charpoly_ql\description@@
a|ell a| integer a| `2` a| @@mod_l_eigenvalues\hecke_algebras_l_adic\ell\description@@
a|field a| collection of mixed types a| `[2, 4, u'x^4 + x + 1', 1]` a| @@mod_l_eigenvalues\hecke_algebras_l_adic\field\description@@
a|gen_l a| Record cannot be found containing key a| `N/A` a| @@mod_l_eigenvalues\hecke_algebras_l_adic\gen_l\description@@
a|idempotent a| string a| `[[ 1, 0 ],[ 0, 1 ]]` a| @@mod_l_eigenvalues\hecke_algebras_l_adic\idempotent\description@@
a|index a| integer a| `1` a| @@mod_l_eigenvalues\hecke_algebras_l_adic\index\description@@
a|label_l a| string a| `23.2.1.1.3.1` a| @@mod_l_eigenvalues\hecke_algebras_l_adic\label_l\description@@
a|level a| integer a| `1` a| @@mod_l_eigenvalues\hecke_algebras_l_adic\level\description@@
a|num_charpoly_ql a| integer a| `1` a| @@mod_l_eigenvalues\hecke_algebras_l_adic\num_charpoly_ql\description@@
a|num_gen_l a| Record cannot be found containing key a| `N/A` a| @@mod_l_eigenvalues\hecke_algebras_l_adic\num_gen_l\description@@
a|operators a| collection of integer a| `[[1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1], [0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1],` ... a| @@mod_l_eigenvalues\hecke_algebras_l_adic\operators\description@@
a|orbit_label a| string a| `23.2.1.1` a| @@mod_l_eigenvalues\hecke_algebras_l_adic\orbit_label\description@@
a|properties a| collection of real a| `[[1], 0]` a| @@mod_l_eigenvalues\hecke_algebras_l_adic\properties\description@@
a|rel_l a| Record cannot be found containing key a| `N/A` a| @@mod_l_eigenvalues\hecke_algebras_l_adic\rel_l\description@@
a|structure a| collection of mixed types a| `[1, 0, u'[]', u'[]']` a| @@mod_l_eigenvalues\hecke_algebras_l_adic\structure\description@@
a|weight a| integer a| `2` a| @@mod_l_eigenvalues\hecke_algebras_l_adic\weight\description@@
|==============================

'''

== List of indices ==

[width="90%", options="header", ]
|==============================
a|Index Name a| Index fields
a|_id_ a| _id sorted ascending
a|ell_1 a| ell sorted ascending
a|level_1 a| level sorted ascending
a|weight_1 a| weight sorted ascending
|==============================

'''

== List of record types in the database ==

2 distinct record types are present.

****
[discrete]
=== Base record : @@mod_l_eigenvalues\hecke_algebras_l_adic\45467c16876c75de26d6818dbf7cf1cd\name@@ ===

[NOTE]
====
The base record represents the smallest intersection of all related records.

@@mod_l_eigenvalues\hecke_algebras_l_adic\45467c16876c75de26d6818dbf7cf1cd\description@@
====

3754 records of base type in collection

* charpoly_ql 
* ell 
* gen_l 
* idempotent 
* index 
* label_l 
* level 
* num_charpoly_ql 
* num_gen_l 
* orbit_label 
* rel_l 
* weight 



****

'''

=== Derived records ===

[NOTE]
====
Derived records are the record types that actually exist in the database.They are represented as differences from the base record
====

****
[discrete]
=== @@mod_l_eigenvalues\hecke_algebras_l_adic\9130b5310c421488c3eba35173547602\name@@ ===

[NOTE]
====
@@mod_l_eigenvalues\hecke_algebras_l_adic\9130b5310c421488c3eba35173547602\description@@


====

17 records extended from base type

* field 
* operators 
* properties 
* structure 



****

'''

== Notes ==

@@mod_l_eigenvalues\hecke_algebras_l_adic\(NOTES)\description@@

