= Database report for modularforms2\webnewforms =

Prepared with the lmfdb asciidoc report tool

Christopher Brady <C.S.Brady@Warwick.ac.uk>

Version 1.0.0

'''

== Collection information ==

[width="50%", ]
|==============================
a|*Description* a| Description: Json data for a Newform object of type 'WebNewform' as defined in '/modular_forms/elliptic_modular_forms/backend/web_newforms.py'
a|*Status* a| http://www.lmfdb.org/ModularForm/GL2/Q/holomorphic/[production]
a|*Contact* a| https://github.com/sehlen[Stefan Ehlen] , https://github.com/fredstro[Fredrik Strömberg]
a|*Code* a| https://github.com/LMFDB/lmfdb/tree/master/lmfdb/modular_forms/elliptic_modular_forms[modular_forms/elliptic_modular_forms]
|==============================

== List of keys in the database ==

The following keys appear in at least one record in the database

[WARNING]
====
The type of the keys is inferred from only one record in the database. If the key can have different types in different records this type will be inaccurate
Only the first 100 characters of the example record are shown
====

[width="90%", options="header", ]
|==============================
a|Key a| Inferred Type a| Example record a| Description
a|_coefficients a| collection of mixed types a| `{u'elt_type': u'rational', u'coeff_cplxty': 3, u'nv_coeff_norm': u'18', u'nv_coeff_index': 2, u'nv_c` ... a| @@modularforms2\webnewforms\_coefficients\description@@
a|absolute_polynomial a| string a| `x` a| the absolute polynomial for the coefficient field
a|base_ring a| string a| `1.1.1.1` a| the base field of the coefficient field. Should be the same as the field in which the character has values (we view the trivial character as having values in Q which has label '1.1.1.1')
a|character a| integer a| `1` a| the character number in the scheme described below
a|character_naming_scheme a| string a| `Conrey` a| The naming scheme of the character used for this object
a|cm_disc a| integer a| `0` a| equals D, the discriminant of the imaginary quadratic field with which this newform has CM if it has CM, else 0
a|coefficient_field a| string a| `1.1.1.1` a| the label (in the format as given by lmfdb number fields) of the coefficient field
a|coefficient_field_degree a| integer a| `1` a| the absolute degree of the coefficient field
a|creation_date a| Type cannot be identified (<type 'datetime.datetime'>) a| `2016-05-30 03:58:00` a| when this record was created
a|dimension a| integer a| `1` a| dimension of this newform as an irreducible submodule of the ambient space
a|fix a| integer a| `1` a| @@modularforms2\webnewforms\fix\description@@
a|hecke_orbit_label a| string a| `1.100.1.a` a| the label of format level.weight.character.label where 'label' is given in the field label below
a|is_cm a| integer a| `0` a| 1 if this newform has CM, else 0
a|is_cuspidal a| integer a| `1` a| 1 if this record corresponds to a cuspidal newform (for future compatibility if Eisenstein series will be included), else 0
a|is_rational a| integer a| `1` a| 1 if this newform has rational Fourier coefficients, else 0
a|label a| string a| `b` a| label of this orbit in the 'Cremona label' convention, i.e. the first (0th in python ordering) orbit has label 'a', the second 'b', the 27-th 'aa' and then 'ab', the 702nd is 'aaa' etc.
a|level a| integer a| `1` a| level
a|modification_date a| Type cannot be identified (<type 'datetime.datetime'>) a| `2016-05-30 03:58:05.300000` a| when this record was last modified
a|parent a| string a| `1.100.1` a| label of form label.weight.character of the space which contains the given newform (corresponding to the key 'space_label' in the collection webmodformspace)
a|prec a| integer a| `110` a| number of coefficients in the stored q-expansion (either in this record or in the gridfs record)
a|q_expansion a| string a| `q + 18*q^2 + 81*q^3 - 188*q^4 - 1530*q^5 + 1458*q^6 + 9128*q^7 - 12600*q^8 + 6561*q^9 - 27540*q^10 +` ... a| string formatted q-expansion of this newform (if not stored here it is taken from the gridfs object in webmodformspace.files)
a|sage_version a| Record cannot be found containing key a| `N/A` a| @@modularforms2\webnewforms\sage_version\description@@
a|version a| real a| `1.3` a| version number
a|weight a| integer a| `10` a| weight
|==============================

'''

== List of indices ==

[width="90%", options="header", ]
|==============================
a|Index Name a| Index fields
a|hecke_orbit_label_1 a| hecke_orbit_label sorted ascending
a|level_1_weight_1_chi_1 a| level sorted ascending, weight sorted ascending, chi sorted ascending
a|_id_ a| _id sorted ascending
a|hecke_orbit_label_1_version_1 a| hecke_orbit_label sorted ascending, version sorted ascending
a|parent_1 a| parent sorted ascending
|==============================

'''

== List of record types in the database ==

8 distinct record types are present.

****
[discrete]
=== Base record ===

[NOTE]
====
The base record represents the smallest intersection of all related records.


====

Base record class does not exist in the database. Please consult the derived records section below to see all of the classes in the database

* absolute_polynomial 
* base_ring 
* character 
* character_naming_scheme 
* cm_disc 
* coefficient_field 
* coefficient_field_degree 
* creation_date 
* dimension 
* hecke_orbit_label 
* is_cm 
* is_cuspidal 
* is_rational 
* label 
* level 
* modification_date 
* parent 
* q_expansion 
* version 
* weight 



****

'''

=== Derived records ===

[NOTE]
====
Derived records are the record types that actually exist in the database.They are represented as differences from the base record
====

****
[discrete]
=== @@modularforms2\webnewforms\18e9403934aec2eaca13ff2a6d55ae81\name@@ ===

[NOTE]
====
@@modularforms2\webnewforms\18e9403934aec2eaca13ff2a6d55ae81\description@@


====

7499 records extended from base type

* prec 



****

'''

****
[discrete]
=== @@modularforms2\webnewforms\a57ec7d17cb6f08dba54d9b15b464a5d\name@@ ===

[NOTE]
====
@@modularforms2\webnewforms\a57ec7d17cb6f08dba54d9b15b464a5d\description@@


====

653 records extended from base type

* _coefficients 
* prec 
* sage_version 



****

'''

****
[discrete]
=== @@modularforms2\webnewforms\32578ce469df6fb85ab4ec0c8922f026\name@@ ===

[NOTE]
====
@@modularforms2\webnewforms\32578ce469df6fb85ab4ec0c8922f026\description@@


====

134 records extended from base type

* sage_version 



****

'''

****
[discrete]
=== @@modularforms2\webnewforms\562d03d9019da669529795d0bc409004\name@@ ===

[NOTE]
====
@@modularforms2\webnewforms\562d03d9019da669529795d0bc409004\description@@


====

92 records extended from base type

* _coefficients 
* sage_version 



****

'''

****
[discrete]
=== @@modularforms2\webnewforms\b5ff57c52710fb50bc03d3d456168557\name@@ ===

[NOTE]
====
@@modularforms2\webnewforms\b5ff57c52710fb50bc03d3d456168557\description@@


====

73 records extended from base type

* fix 
* prec 



****

'''

****
[discrete]
=== @@modularforms2\webnewforms\0cfdda5c16105dd13a49ad912cf90dc1\name@@ ===

[NOTE]
====
@@modularforms2\webnewforms\0cfdda5c16105dd13a49ad912cf90dc1\description@@


====

31 records extended from base type

* prec 
* sage_version 



****

'''

****
[discrete]
=== @@modularforms2\webnewforms\7a88d3b33b725e4aa083a623b33f01a4\name@@ ===

[NOTE]
====
@@modularforms2\webnewforms\7a88d3b33b725e4aa083a623b33f01a4\description@@


====

22 records extended from base type

* fix 
* prec 
* sage_version 



****

'''

****
[discrete]
=== @@modularforms2\webnewforms\25b949eea7f7cc5419163a170e5fd063\name@@ ===

[NOTE]
====
@@modularforms2\webnewforms\25b949eea7f7cc5419163a170e5fd063\description@@


====

19 records extended from base type

* _coefficients 
* fix 
* prec 
* sage_version 



****

'''

== Notes ==

@@modularforms2\webnewforms\(NOTES)\description@@

