= Database report for modularforms2\dimension_table =

Prepared with the lmfdb asciidoc report tool

Christopher Brady <C.S.Brady@Warwick.ac.uk>

Version 1.0.0

'''

== Collection information ==

[width="50%", ]
|==============================
a|*Description* a| Dimension data for modular forms
a|*Status* a| http://www.lmfdb.org/ModularForm/GL2/Q/holomorphic/[production]
a|*Contact* a| https://github.com/sehlen[Stefan Ehlen] , https://github.com/fredstro[Fredrik Strömberg]
a|*Code* a| https://github.com/LMFDB/lmfdb/tree/master/lmfdb/modular_forms/elliptic_modular_forms[modular_forms/elliptic_modular_forms]
|==============================

== List of keys in the database ==

The following keys appear in at least one record in the database

[WARNING]
====
The type of the keys is inferred from only one record in the database. If the key can have different types in different records this type will be inaccurate
Only the first 100 characters of the example record are shown
====

[width="90%", options="header", ]
|==============================
a|Key a| Inferred Type a| Example record a| Description
a|d_eis a| integer a| `0` a| The dimension of the space of Eisenstein series E_k(Gamma_1(N))
a|all_in_db a| boolean a| `False` a| True if the spaces S_k^{new}(N,chi) for all chi are in the db, False otherwise
a|in_wdb a| integer a| `0` a| is 1 if we have this space in the web database, i.e. an entry exists in the collection webmodformspace and all galois orbits of newforms are stored in the collection webnewforms, else 0
a|d_newf a| integer a| `0` a| 161 ???
a|weight a| integer a| `2` a| the weight of self
a|character_parity a| integer a| `1` a| '1' if the character is even and '-1' if it is odd
a|gamma1_label a| real stored as string a| `43.20` a| A label for the space, of the form level.weight
a|in_msdb a| integer a| `0` a| Equals 1 if this space has a record in the Modular_Symbols.files collection, else 0
a|cchi a| integer a| `9` a| Conrey character number
a|d_cusp a| integer a| `0` a| Dimension of space of cusp forms S_k(N, chi), where N is the level, chi is the character specified by cchi.
a|character_orbit_rep a| integer a| `9` a| The number of the representative of the Galois orbit
a|one_in_wdb a| boolean a| `False` a| True if at least one of these spaces is in the db
a|space_labe; a| string a| `20.12.3` a| Probably a misspelling of 'space_label'
a|character_orbit a| collection of integer a| `[9, 11]` a| List of conrey character numbers of elements of the orbits of 'cchi'
a|d_mod a| integer a| `0` a| The dimension of the space of all modular forms M_k(Gamma_1(N))
a|space_label a| string a| `14.17.9` a| the label of this space of the form N.k.i where N is the level, k the weight and i the Conrey character number
a|level a| integer a| `1` a| The level of the space
a|space_orbit_label a| string a| `14.17.2` a| The label of the Galois orbit of this space of the form N.k.i, where i is the index of the Galois orbit of the character in the list of Galois orbits of characters of this level. The Galois orbits are ordered by the minimal number appearing in the orbit.
|==============================

'''

== List of indices ==

[width="90%", options="header", ]
|==============================
a|Index Name a| Index fields
a|_id_ a| _id sorted ascending
a|level_1_weight_1 a| level sorted ascending, weight sorted ascending
a|level_1 a| level sorted ascending
a|weight_1 a| weight sorted ascending
a|level_1_weight_1_character_orbit_rep_1 a| level sorted ascending, weight sorted ascending, character_orbit_rep sorted ascending
|==============================

'''

== List of record types in the database ==

5 distinct record types are present.

****
[discrete]
=== Base record ===

[NOTE]
====
The base record represents the smallest intersection of all related records.


====

Base record class does not exist in the database. Please consult the derived records section below to see all of the classes in the database

* d_eis 
* d_newf 
* weight 
* level 
* d_cusp 
* d_mod 



****

'''

=== Derived records ===

[NOTE]
====
Derived records are the record types that actually exist in the database.They are represented as differences from the base record
====

****
[discrete]
=== Gamma0 with character ===

[NOTE]
====
@@modularforms2\dimension_table\b1aa1ac40670e9246eb96462a501a748\description@@


====

312477 records extended from base type

* cchi 
* character_orbit 
* character_orbit_rep 
* in_msdb 
* in_wdb 
* space_label 
* space_orbit_label 



****

'''

****
[discrete]
=== @@modularforms2\dimension_table\9bd92621635f5e1eced5f38e19e10ef4\name@@ ===

[NOTE]
====
@@modularforms2\dimension_table\9bd92621635f5e1eced5f38e19e10ef4\description@@


====

86446 records extended from base type

* cchi 
* character_orbit 
* character_orbit_rep 
* character_parity 
* in_msdb 
* in_wdb 
* space_label 
* space_orbit_label 



****

'''

****
[discrete]
=== Gamma1 ===

[NOTE]
====
@@modularforms2\dimension_table\8606c0cf9090be04a30d9adbf5564ce6\description@@


====

19706 records extended from base type

* all_in_db 
* gamma1_label 



****

'''

****
[discrete]
=== Gamma1 ===

[NOTE]
====
@@modularforms2\dimension_table\d8623295b01435bcb0af6606997e6dd6\description@@


====

9351 records extended from base type

* all_in_db 
* gamma1_label 
* one_in_wdb 



****

'''

****
[discrete]
=== Gamma0 with character ===

[NOTE]
====
@@modularforms2\dimension_table\a7453a23b1c15b55f4723c92497f8eef\description@@


====

1 records extended from base type

* cchi 
* character_orbit 
* character_orbit_rep 
* character_parity 
* in_msdb 
* in_wdb 
* space_labe; 
* space_label 
* space_orbit_label 



****

'''

== Notes ==

@@modularforms2\dimension_table\(NOTES)\description@@

