= Database report for sato_tate_groups\small_groups =

Prepared with the lmfdb asciidoc report tool

Christopher Brady <C.S.Brady@Warwick.ac.uk>

Version 1.0.0

'''

== Collection information ==

[width="50%", ]
|==============================
a|*Description* a| Sato-Tate groups
a|*Status* a| http://www.lmfdb.org/SatoTateGroup[production]
a|*Contact* a| https://github.com/AndrewVSutherland[Andrew Sutherland]
a|*Code* a| https://github.com/LMFDB/lmfdb/tree/master/lmfdb/sato_tate_groups/[sato_tate_groups]
|==============================

== List of keys in the database ==

The following keys appear in at least one record in the database

[WARNING]
====
The type of the keys is inferred from only one record in the database. If the key can have different types in different records this type will be inaccurate
Only the first 100 characters of the example record are shown
====

[width="90%", options="header", ]
|==============================
a|Key a| Inferred Type a| Example record a| Description
a|perfect a| boolean a| `False` a| true if the group is perfect, false otherwise
a|abelian a| boolean a| `True` a| true if the group is abelian, false otherwise
a|exponent a| integer a| `4` a| @@sato_tate_groups\small_groups\exponent\description@@
a|cyclic a| boolean a| `True` a| true if the group is cyclic, false otherwise
a|simple a| boolean a| `False` a| true if the group is simple, false otherwise
a|label a| real stored as string a| `1.1` a| GAP ID encoded as a string u'N.n', where N is the order of the group and n distinguishes groups of the same order (as determined in GAP).
a|pretty a| string a| `C_4` a| pretty-print version of the name in latex math mode
a|solvable a| boolean a| `True` a| true if the group is solvable, false otherwise
a|order a| integer a| `1` a| order of the group (positive integer)
a|name a| string a| `((C2*C6).D4):C2` a| text discription of the group
|==============================

'''

== List of indices ==

[width="90%", options="header", ]
|==============================
a|Index Name a| Index fields
a|name_1 a| name sorted ascending
a|_id_ a| _id sorted ascending
a|order_1 a| order sorted ascending
a|label_1 a| label sorted ascending
|==============================

'''

== List of record types in the database ==

****
[discrete]
=== All records ===

[NOTE]
====
7012 records of type
====

* abelian 
* cyclic 
* exponent 
* label 
* name 
* order 
* perfect 
* pretty 
* simple 
* solvable 



****

'''

== Notes ==

Extent: All groups of order up to 255 (up to isomorphism). Easy to add more (up to order 1024).

