= Database report for transitivegroups\groups =

Prepared with the lmfdb asciidoc report tool

Christopher Brady <C.S.Brady@Warwick.ac.uk>

Version 1.0.0

'''

== Collection information ==

[width="50%", ]
|==============================
a|*Description* a| Galois groups
a|*Status* a| http://www.lmfdb.org/GaloisGroup[production]
a|*Contact* a| https://github.com/jwj61[John Jones]
a|*Code* a| https://github.com/LMFDB/lmfdb/tree/master/lmfdb/galois_groups[galois_groups]
|==============================

== List of keys in the database ==

The following keys appear in at least one record in the database

[WARNING]
====
The type of the keys is inferred from only one record in the database. If the key can have different types in different records this type will be inaccurate
Only the first 100 characters of the example record are shown
====

[width="90%", options="header", ]
|==============================
a|Key a| Inferred Type a| Example record a| Description
a|ab a| integer a| `1`
 a| @@transitivegroups\groups\ab\description@@
a|arith_equiv a| integer a| `0`
 a| number of arithmetically equivalent fields for number fields with this Galois group
a|auts a| integer a| `1`
 a| the number of automorphisms a degree n field with this as its Galois group
a|cyc a| integer a| `1`
 a| 1 if the group is cyclic, otherwise 0
a|label a| string a| `1T1`
 a| label is of the form nTt where n is the degree and t is the "t-number"
a|moddecompuniq a| collection of integer a| `[0]`
 a| @@transitivegroups\groups\moddecompuniq\description@@
a|n a| integer a| `1`
 a| the degree (n from S_n)
a|name a| string a| `Trivial group`
 a| the name given by gap (also used by pari, magma, sage, etc)
a|order a| integer stored as string a| `1`
 a| the size of the group
a|parity a| integer a| `1`
 a| 1 if the group is a subgroup of A_n, otherwise -1
a|pretty a| string a| `Trivial`
 a| latex of a nicer name for this group
a|prim a| integer a| `1`
 a| @@transitivegroups\groups\prim\description@@
a|repns a| list of pairs [n,t] a| `[]`
 a| if K is a degree n field with this Galois group, this gives other small degree fields with the same Galois closure, up to isomorphism, in terms of their Galois groups
a|resolve a| list of pairs [n,t] a| `[]`
 a| 
a|solv a| integer a| `1`
 a| 1 if the group is solvable, otherwise 0
a|subs a| list of pairs [n,t] a| `[]`
 a|  if K is a degree n field with this Galois group, this gives the subfields up to isomorphism in terms of their Galois groups
a|t a| integer a| `1`
 a| the t-number, a standard index for conjugacy classes of subgroups of S_n
|==============================

'''

== List of indices ==

[width="90%", options="header", ]
|==============================
a|Index Name a| Index fields
a|n_1_t_1 a| n sorted ascending, t sorted ascending
a|_id_ a| _id sorted ascending
a|t_1 a| t sorted ascending
a|metadata_1 a| metadata sorted ascending
|==============================

'''

== List of record types in the database ==

2 distinct record types are present.

****
[discrete]
=== Base record : @@transitivegroups\groups\8f3fdb9f01020fbf6a232ccd19fe03ac\name@@ ===

[NOTE]
====
The base record represents the smallest intersection of all related records.

@@transitivegroups\groups\8f3fdb9f01020fbf6a232ccd19fe03ac\description@@
====

4944 records of base type in collection

* parity 
* ab 
* prim 
* name 
* repns 
* n 
* cyc 
* pretty 
* resolve 
* auts 
* arith_equiv 
* t 
* solv 
* label 
* order 
* subs 



****

'''

=== Derived records ===

[NOTE]
====
Derived records are the record types that actually exist in the database.They are represented as differences from the base record
====

****
[discrete]
=== @@transitivegroups\groups\57ddb3521a5ac481cabcce4956eeb8cb\name@@ ===

[NOTE]
====
@@transitivegroups\groups\57ddb3521a5ac481cabcce4956eeb8cb\description@@


====

9 records extended from base type

* moddecompuniq 



****

'''

== Notes ==

@@transitivegroups\groups\(NOTES)\description@@

