= Database report for transitivegroups\Gmodules =

Prepared with the lmfdb asciidoc report tool

Christopher Brady <C.S.Brady@Warwick.ac.uk>

Version 1.0.0

'''

== Collection information ==

[width="50%", ]
|==============================
a|*Description* a| Galois groups
a|*Status* a| http://www.lmfdb.org/GaloisGroup[production]
a|*Contact* a| https://github.com/jwj61[John Jones]
a|*Code* a| https://github.com/LMFDB/lmfdb/tree/master/lmfdb/galois_groups[galois_groups]
|==============================

== List of keys in the database ==

The following keys appear in at least one record in the database

[WARNING]
====
The type of the keys is inferred from only one record in the database. If the key can have different types in different records this type will be inaccurate
Only the first 100 characters of the example record are shown
====

[width="90%", options="header", ]
|==============================
a|Key a| Inferred Type a| Example record a| Description
a|complete a| integer a| `1`
 a| Do we have complete information, 1 for yes, 0 for no
a|dim a| integer a| `1`
 a| dimension of lattice
a|gens a| pair [string of cycle type, matrix for action] a| `[[u'(1,2,3)', [[1]]], [u'(1,2)', [[1]]]]`
 a| generators of group and matrix for their actions
a|index a| integer a| `0`
 a| index to identify the G-module
a|n a| integer a| `3`
 a| for Galois group in form nTt
a|name a| string a| `Triv`
 a| name of this G-module
a|t a| integer a| `2`
 a| for Galois group in form nTt
|==============================

'''

== List of indices ==

[width="90%", options="header", ]
|==============================
a|Index Name a| Index fields
a|_id_ a| _id sorted ascending
|==============================

'''

== List of record types in the database ==

2 distinct record types are present.

****
[discrete]
=== Base record : @@transitivegroups\Gmodules\2efbc4292db323d1514f3cb48e2bde04\name@@ ===

[NOTE]
====
The base record represents the smallest intersection of all related records.

@@transitivegroups\Gmodules\2efbc4292db323d1514f3cb48e2bde04\description@@
====

38 records of base type in collection

* dim 
* name 
* index 
* gens 
* n 
* t 



****

'''

=== Derived records ===

[NOTE]
====
Derived records are the record types that actually exist in the database.They are represented as differences from the base record
====

****
[discrete]
=== @@transitivegroups\Gmodules\fa757152aecf89ca2cf274d6fc5cba29\name@@ ===

[NOTE]
====
@@transitivegroups\Gmodules\fa757152aecf89ca2cf274d6fc5cba29\description@@


====

35 records extended from base type

* complete 



****

'''

== Notes ==

Each Gmodule is uniqely determined by a Galois group (nTt) and then an abitrary index.

